const AUTH_SUCCESS = 'AUTH_SUCCESS';
const AUTH_FAIL = 'AUTH_FAIL';
const AUTH_CLEAR = 'AUTH_CLEAR';

const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
const REGISTER_FAIL = 'REGISTER_FAIL';
const REGISTER_CLEAR = 'REGISTER_CLEAR';

export {
    AUTH_SUCCESS,
    AUTH_FAIL,
    AUTH_CLEAR,
    REGISTER_SUCCESS,
    REGISTER_FAIL,
    REGISTER_CLEAR
}