const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGIN_FAIL = 'LOGIN_FAIL';
const LOGIN_CLEAR = 'LOGIN_CLEAR';

const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
const REGISTER_FAIL = 'REGISTER_FAIL';
const REGISTER_CLEAR = 'REGISTER_CLEAR';

export {
    LOGIN_SUCCESS,
    LOGIN_FAIL,
    LOGIN_CLEAR,
    REGISTER_SUCCESS,
    REGISTER_FAIL,
    REGISTER_CLEAR
}